### ISSUE TITLE
Musical Talent

### ISSUE THREAD

**Issue by NovaThatGuy** [StarboundGames/Side-Scrolling-Adventure-Game#11]
Can you make some killer music? If so Great we could really use your help and support. If you are willing and able please make some sample/finished songs for the game.

**Comment by JustANormalGitter** [comment]
The music should also be open to review, so that everyone thinks it will appeal to the game and the theme. We have people working on this team that have different tastes in games, but the keyword is GAMES. The music should fit with the game, and have the right beat and tone
