### ISSUE TITLE
Game Mechanics

### ISSUE THREAD

**Issue by NovaThatGuy** [StarboundGames/Side-Scrolling-Adventure-Game#8]
I am working on the mechanics of the game and really could use some help. 
If you're interested in helping, you can help by doing some of the things on the list bellow.

- Collision Detection
- Movement
- Combat
- Loading Screens
- HUD
- Health And Mana System
- Saving And Loading

If anyone can help with these I would be greatful.

**Comment by JustANormalGitter** [comment]
This will go into the engine right?

**Comment by NovaThatGuy** [comment]
Uh... No. It would be inside the "Game.class" You may want to learn a little about Java. Also we don't have a actual engine. Its pure Java.
